/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StudentId = IDL.Text;
export const ActivityRecord = IDL.Record({
  'activityType' : IDL.Text,
  'studentId' : StudentId,
  'description' : IDL.Text,
  'session' : IDL.Text,
  'grade' : IDL.Text,
  'remarks' : IDL.Text,
});
export const LowerClassMarks = IDL.Record({
  'totalMarks' : IDL.Float64,
  'subjectName' : IDL.Text,
  'writtenTest1' : IDL.Float64,
  'writtenTest2' : IDL.Float64,
  'writtenTest3' : IDL.Float64,
  'writtenTest4' : IDL.Float64,
  'grade' : IDL.Text,
  'comprehensiveTest1' : IDL.Float64,
  'comprehensiveTest2' : IDL.Float64,
  'comprehensiveTest3' : IDL.Float64,
  'comprehensiveTest4' : IDL.Float64,
  'percentage' : IDL.Float64,
});
export const UpperClassMarks = IDL.Record({
  'nb1' : IDL.Float64,
  'nb2' : IDL.Float64,
  'pt1' : IDL.Float64,
  'pt2' : IDL.Float64,
  'se1' : IDL.Float64,
  'se2' : IDL.Float64,
  'term2Total' : IDL.Float64,
  'subjectName' : IDL.Text,
  'term2Exam' : IDL.Float64,
  'finalPercentage' : IDL.Float64,
  'pt2Weightage' : IDL.Float64,
  'grade' : IDL.Text,
  'pt1Weightage' : IDL.Float64,
  'term1Exam' : IDL.Float64,
  'term1Total' : IDL.Float64,
});
export const SubjectMarks = IDL.Variant({
  'lowerClass' : LowerClassMarks,
  'upperClass' : UpperClassMarks,
});
export const ReportCard = IDL.Record({
  'studentId' : StudentId,
  'term2Total' : IDL.Float64,
  'behaviour' : IDL.Text,
  'rank' : IDL.Text,
  'finalPercentage' : IDL.Float64,
  'session' : IDL.Text,
  'sportsRemarks' : IDL.Text,
  'grade' : IDL.Text,
  'attendanceSummary' : IDL.Text,
  'term1Total' : IDL.Float64,
  'remarks' : IDL.Text,
});
export const MonthlyAttendance = IDL.Record({
  'month' : IDL.Text,
  'studentId' : StudentId,
  'present' : IDL.Nat,
  'totalDays' : IDL.Nat,
  'session' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const SportsRecord = IDL.Record({
  'studentId' : StudentId,
  'game' : IDL.Text,
  'level' : IDL.Text,
  'event' : IDL.Text,
  'entryId' : IDL.Text,
  'session' : IDL.Text,
  'position' : IDL.Text,
  'remarks' : IDL.Text,
});
export const StudentProfile = IDL.Record({
  'pen' : IDL.Text,
  'tribe' : IDL.Text,
  'contact' : IDL.Text,
  'studentId' : StudentId,
  'dateOfBirth' : IDL.Text,
  'heightReopening' : IDL.Float64,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'motherName' : IDL.Text,
  'heightClosure' : IDL.Float64,
  'weightClosure' : IDL.Float64,
  'session' : IDL.Text,
  'fatherName' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Text,
  'classLevel' : IDL.Nat,
  'rollNo' : IDL.Text,
  'religion' : IDL.Text,
  'aadhar' : IDL.Text,
  'weightReopening' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'studentId' : IDL.Opt(StudentId),
  'name' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StudyMaterial = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'comments' : IDL.Text,
  'uploadedBy' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getActivityRecords' : IDL.Func(
      [StudentId],
      [IDL.Vec(ActivityRecord)],
      ['query'],
    ),
  'getAllRecordsForStudent' : IDL.Func(
      [StudentId],
      [
        IDL.Record({
          'marks' : IDL.Vec(SubjectMarks),
          'reportCards' : IDL.Vec(ReportCard),
          'activities' : IDL.Vec(ActivityRecord),
          'attendance' : IDL.Vec(MonthlyAttendance),
          'sports' : IDL.Vec(SportsRecord),
          'profile' : StudentProfile,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMonthlyAttendance' : IDL.Func(
      [StudentId],
      [IDL.Vec(MonthlyAttendance)],
      ['query'],
    ),
  'getReportCards' : IDL.Func([StudentId], [IDL.Vec(ReportCard)], ['query']),
  'getSportsRecords' : IDL.Func(
      [StudentId],
      [IDL.Vec(SportsRecord)],
      ['query'],
    ),
  'getStudentProfile' : IDL.Func([StudentId], [StudentProfile], ['query']),
  'getStudentsByClass' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(StudentProfile)],
      ['query'],
    ),
  'getStudyMaterial' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(StudyMaterial)],
      ['query'],
    ),
  'getSubjectMarks' : IDL.Func([StudentId], [IDL.Vec(SubjectMarks)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllStudentProfiles' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'listAllStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
  'saveActivityRecord' : IDL.Func([StudentId, ActivityRecord], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMonthlyAttendance' : IDL.Func([StudentId, MonthlyAttendance], [], []),
  'saveReportCard' : IDL.Func([StudentId, ReportCard], [], []),
  'saveSportsRecord' : IDL.Func([StudentId, SportsRecord], [], []),
  'saveStudentProfile' : IDL.Func([StudentProfile], [], []),
  'saveSubjectMarks' : IDL.Func([StudentId, IDL.Vec(SubjectMarks)], [], []),
  'searchStudents' : IDL.Func([IDL.Text], [IDL.Vec(StudentProfile)], ['query']),
  'uploadStudyMaterial' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StudentId = IDL.Text;
  const ActivityRecord = IDL.Record({
    'activityType' : IDL.Text,
    'studentId' : StudentId,
    'description' : IDL.Text,
    'session' : IDL.Text,
    'grade' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const LowerClassMarks = IDL.Record({
    'totalMarks' : IDL.Float64,
    'subjectName' : IDL.Text,
    'writtenTest1' : IDL.Float64,
    'writtenTest2' : IDL.Float64,
    'writtenTest3' : IDL.Float64,
    'writtenTest4' : IDL.Float64,
    'grade' : IDL.Text,
    'comprehensiveTest1' : IDL.Float64,
    'comprehensiveTest2' : IDL.Float64,
    'comprehensiveTest3' : IDL.Float64,
    'comprehensiveTest4' : IDL.Float64,
    'percentage' : IDL.Float64,
  });
  const UpperClassMarks = IDL.Record({
    'nb1' : IDL.Float64,
    'nb2' : IDL.Float64,
    'pt1' : IDL.Float64,
    'pt2' : IDL.Float64,
    'se1' : IDL.Float64,
    'se2' : IDL.Float64,
    'term2Total' : IDL.Float64,
    'subjectName' : IDL.Text,
    'term2Exam' : IDL.Float64,
    'finalPercentage' : IDL.Float64,
    'pt2Weightage' : IDL.Float64,
    'grade' : IDL.Text,
    'pt1Weightage' : IDL.Float64,
    'term1Exam' : IDL.Float64,
    'term1Total' : IDL.Float64,
  });
  const SubjectMarks = IDL.Variant({
    'lowerClass' : LowerClassMarks,
    'upperClass' : UpperClassMarks,
  });
  const ReportCard = IDL.Record({
    'studentId' : StudentId,
    'term2Total' : IDL.Float64,
    'behaviour' : IDL.Text,
    'rank' : IDL.Text,
    'finalPercentage' : IDL.Float64,
    'session' : IDL.Text,
    'sportsRemarks' : IDL.Text,
    'grade' : IDL.Text,
    'attendanceSummary' : IDL.Text,
    'term1Total' : IDL.Float64,
    'remarks' : IDL.Text,
  });
  const MonthlyAttendance = IDL.Record({
    'month' : IDL.Text,
    'studentId' : StudentId,
    'present' : IDL.Nat,
    'totalDays' : IDL.Nat,
    'session' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const SportsRecord = IDL.Record({
    'studentId' : StudentId,
    'game' : IDL.Text,
    'level' : IDL.Text,
    'event' : IDL.Text,
    'entryId' : IDL.Text,
    'session' : IDL.Text,
    'position' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const StudentProfile = IDL.Record({
    'pen' : IDL.Text,
    'tribe' : IDL.Text,
    'contact' : IDL.Text,
    'studentId' : StudentId,
    'dateOfBirth' : IDL.Text,
    'heightReopening' : IDL.Float64,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'motherName' : IDL.Text,
    'heightClosure' : IDL.Float64,
    'weightClosure' : IDL.Float64,
    'session' : IDL.Text,
    'fatherName' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Text,
    'classLevel' : IDL.Nat,
    'rollNo' : IDL.Text,
    'religion' : IDL.Text,
    'aadhar' : IDL.Text,
    'weightReopening' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'studentId' : IDL.Opt(StudentId),
    'name' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StudyMaterial = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'comments' : IDL.Text,
    'uploadedBy' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getActivityRecords' : IDL.Func(
        [StudentId],
        [IDL.Vec(ActivityRecord)],
        ['query'],
      ),
    'getAllRecordsForStudent' : IDL.Func(
        [StudentId],
        [
          IDL.Record({
            'marks' : IDL.Vec(SubjectMarks),
            'reportCards' : IDL.Vec(ReportCard),
            'activities' : IDL.Vec(ActivityRecord),
            'attendance' : IDL.Vec(MonthlyAttendance),
            'sports' : IDL.Vec(SportsRecord),
            'profile' : StudentProfile,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMonthlyAttendance' : IDL.Func(
        [StudentId],
        [IDL.Vec(MonthlyAttendance)],
        ['query'],
      ),
    'getReportCards' : IDL.Func([StudentId], [IDL.Vec(ReportCard)], ['query']),
    'getSportsRecords' : IDL.Func(
        [StudentId],
        [IDL.Vec(SportsRecord)],
        ['query'],
      ),
    'getStudentProfile' : IDL.Func([StudentId], [StudentProfile], ['query']),
    'getStudentsByClass' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'getStudyMaterial' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StudyMaterial)],
        ['query'],
      ),
    'getSubjectMarks' : IDL.Func(
        [StudentId],
        [IDL.Vec(SubjectMarks)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllStudentProfiles' : IDL.Func(
        [],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'listAllStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
    'saveActivityRecord' : IDL.Func([StudentId, ActivityRecord], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMonthlyAttendance' : IDL.Func([StudentId, MonthlyAttendance], [], []),
    'saveReportCard' : IDL.Func([StudentId, ReportCard], [], []),
    'saveSportsRecord' : IDL.Func([StudentId, SportsRecord], [], []),
    'saveStudentProfile' : IDL.Func([StudentProfile], [], []),
    'saveSubjectMarks' : IDL.Func([StudentId, IDL.Vec(SubjectMarks)], [], []),
    'searchStudents' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'uploadStudyMaterial' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };