/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityRecord {
  'activityType' : string,
  'studentId' : StudentId,
  'description' : string,
  'session' : string,
  'grade' : string,
  'remarks' : string,
}
export type ExternalBlob = Uint8Array;
export interface LowerClassMarks {
  'totalMarks' : number,
  'subjectName' : string,
  'writtenTest1' : number,
  'writtenTest2' : number,
  'writtenTest3' : number,
  'writtenTest4' : number,
  'grade' : string,
  'comprehensiveTest1' : number,
  'comprehensiveTest2' : number,
  'comprehensiveTest3' : number,
  'comprehensiveTest4' : number,
  'percentage' : number,
}
export interface MonthlyAttendance {
  'month' : string,
  'studentId' : StudentId,
  'present' : bigint,
  'totalDays' : bigint,
  'session' : string,
  'percentage' : number,
}
export interface ReportCard {
  'studentId' : StudentId,
  'term2Total' : number,
  'behaviour' : string,
  'rank' : string,
  'finalPercentage' : number,
  'session' : string,
  'sportsRemarks' : string,
  'grade' : string,
  'attendanceSummary' : string,
  'term1Total' : number,
  'remarks' : string,
}
export interface SportsRecord {
  'studentId' : StudentId,
  'game' : string,
  'level' : string,
  'event' : string,
  'entryId' : string,
  'session' : string,
  'position' : string,
  'remarks' : string,
}
export type StudentId = string;
export interface StudentProfile {
  'pen' : string,
  'tribe' : string,
  'contact' : string,
  'studentId' : StudentId,
  'dateOfBirth' : string,
  'heightReopening' : number,
  'name' : string,
  'section' : string,
  'motherName' : string,
  'heightClosure' : number,
  'weightClosure' : number,
  'session' : string,
  'fatherName' : string,
  'address' : string,
  'gender' : string,
  'classLevel' : bigint,
  'rollNo' : string,
  'religion' : string,
  'aadhar' : string,
  'weightReopening' : number,
}
export interface StudyMaterial {
  'id' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'comments' : string,
  'uploadedBy' : Principal,
}
export type SubjectMarks = { 'lowerClass' : LowerClassMarks } |
  { 'upperClass' : UpperClassMarks };
export interface UpperClassMarks {
  'nb1' : number,
  'nb2' : number,
  'pt1' : number,
  'pt2' : number,
  'se1' : number,
  'se2' : number,
  'term2Total' : number,
  'subjectName' : string,
  'term2Exam' : number,
  'finalPercentage' : number,
  'pt2Weightage' : number,
  'grade' : string,
  'pt1Weightage' : number,
  'term1Exam' : number,
  'term1Total' : number,
}
export interface UserProfile { 'studentId' : [] | [StudentId], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getActivityRecords' : ActorMethod<[StudentId], Array<ActivityRecord>>,
  'getAllRecordsForStudent' : ActorMethod<
    [StudentId],
    {
      'marks' : Array<SubjectMarks>,
      'reportCards' : Array<ReportCard>,
      'activities' : Array<ActivityRecord>,
      'attendance' : Array<MonthlyAttendance>,
      'sports' : Array<SportsRecord>,
      'profile' : StudentProfile,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMonthlyAttendance' : ActorMethod<[StudentId], Array<MonthlyAttendance>>,
  'getReportCards' : ActorMethod<[StudentId], Array<ReportCard>>,
  'getSportsRecords' : ActorMethod<[StudentId], Array<SportsRecord>>,
  'getStudentProfile' : ActorMethod<[StudentId], StudentProfile>,
  'getStudentsByClass' : ActorMethod<[bigint], Array<StudentProfile>>,
  'getStudyMaterial' : ActorMethod<[string], [] | [StudyMaterial]>,
  'getSubjectMarks' : ActorMethod<[StudentId], Array<SubjectMarks>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllStudentProfiles' : ActorMethod<[], Array<StudentProfile>>,
  'listAllStudyMaterials' : ActorMethod<[], Array<StudyMaterial>>,
  'saveActivityRecord' : ActorMethod<[StudentId, ActivityRecord], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMonthlyAttendance' : ActorMethod<
    [StudentId, MonthlyAttendance],
    undefined
  >,
  'saveReportCard' : ActorMethod<[StudentId, ReportCard], undefined>,
  'saveSportsRecord' : ActorMethod<[StudentId, SportsRecord], undefined>,
  'saveStudentProfile' : ActorMethod<[StudentProfile], undefined>,
  'saveSubjectMarks' : ActorMethod<[StudentId, Array<SubjectMarks>], undefined>,
  'searchStudents' : ActorMethod<[string], Array<StudentProfile>>,
  'uploadStudyMaterial' : ActorMethod<
    [string, string, ExternalBlob, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];