/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserAccount = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'password' : IDL.Text,
  'role' : IDL.Text,
  'assignedClass' : IDL.Opt(IDL.Nat),
});
export const StudentId = IDL.Text;
export const ActivityRecord = IDL.Record({
  'activityType' : IDL.Text,
  'studentId' : StudentId,
  'description' : IDL.Text,
  'session' : IDL.Text,
  'grade' : IDL.Text,
  'remarks' : IDL.Text,
});
export const LowerClassMarks = IDL.Record({
  'totalMarks' : IDL.Float64,
  'subjectName' : IDL.Text,
  'writtenTest1' : IDL.Float64,
  'writtenTest2' : IDL.Float64,
  'writtenTest3' : IDL.Float64,
  'writtenTest4' : IDL.Float64,
  'grade' : IDL.Text,
  'comprehensiveTest1' : IDL.Float64,
  'comprehensiveTest2' : IDL.Float64,
  'comprehensiveTest3' : IDL.Float64,
  'comprehensiveTest4' : IDL.Float64,
  'percentage' : IDL.Float64,
});
export const UpperClassMarks = IDL.Record({
  'nb1' : IDL.Float64,
  'nb2' : IDL.Float64,
  'pt1' : IDL.Float64,
  'pt2' : IDL.Float64,
  'se1' : IDL.Float64,
  'se2' : IDL.Float64,
  'term2Total' : IDL.Float64,
  'subjectName' : IDL.Text,
  'term2Exam' : IDL.Float64,
  'finalPercentage' : IDL.Float64,
  'pt2Weightage' : IDL.Float64,
  'grade' : IDL.Text,
  'pt1Weightage' : IDL.Float64,
  'term1Exam' : IDL.Float64,
  'term1Total' : IDL.Float64,
});
export const SubjectMarks = IDL.Variant({
  'lowerClass' : LowerClassMarks,
  'upperClass' : UpperClassMarks,
});
export const ReportCard = IDL.Record({
  'studentId' : StudentId,
  'term2Total' : IDL.Float64,
  'behaviour' : IDL.Text,
  'rank' : IDL.Text,
  'finalPercentage' : IDL.Float64,
  'session' : IDL.Text,
  'sportsRemarks' : IDL.Text,
  'grade' : IDL.Text,
  'attendanceSummary' : IDL.Text,
  'term1Total' : IDL.Float64,
  'remarks' : IDL.Text,
});
export const MonthlyAttendance = IDL.Record({
  'month' : IDL.Text,
  'studentId' : StudentId,
  'present' : IDL.Nat,
  'totalDays' : IDL.Nat,
  'session' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const SportsRecord = IDL.Record({
  'studentId' : StudentId,
  'game' : IDL.Text,
  'level' : IDL.Text,
  'event' : IDL.Text,
  'entryId' : IDL.Text,
  'session' : IDL.Text,
  'position' : IDL.Text,
  'remarks' : IDL.Text,
});
export const StudentProfile = IDL.Record({
  'pen' : IDL.Text,
  'tribe' : IDL.Text,
  'contact' : IDL.Text,
  'studentId' : StudentId,
  'dateOfBirth' : IDL.Text,
  'heightReopening' : IDL.Float64,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'motherName' : IDL.Text,
  'heightClosure' : IDL.Float64,
  'weightClosure' : IDL.Float64,
  'session' : IDL.Text,
  'fatherName' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Text,
  'classLevel' : IDL.Nat,
  'rollNo' : IDL.Text,
  'religion' : IDL.Text,
  'aadhar' : IDL.Text,
  'weightReopening' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'studentId' : IDL.Opt(StudentId),
  'name' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StudyMaterial = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'comments' : IDL.Text,
  'uploadedBy' : IDL.Principal,
});
export const Circular = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'fileBlob' : ExternalBlob,
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'uploadedAt' : IDL.Text,
  'uploadedBy' : IDL.Text,
});
export const ClassStudyMaterial = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'fileBlob' : ExternalBlob,
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'classLevel' : IDL.Nat,
  'uploadedAt' : IDL.Text,
  'uploadedBy' : IDL.Text,
});
export const NoticePost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'hasFile' : IDL.Bool,
  'postedAt' : IDL.Text,
  'postedBy' : IDL.Text,
  'content' : IDL.Text,
  'fileBlob' : IDL.Opt(ExternalBlob),
  'fileName' : IDL.Text,
});
export const SessionInfo = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'role' : IDL.Text,
  'assignedClass' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUserAccount' : IDL.Func([IDL.Text, UserAccount], [], []),
  'deleteCircular' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteClassStudyMaterial' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteNotice' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteStudentProfileWithSession' : IDL.Func([IDL.Text, StudentId], [], []),
  'archiveStudentProfileWithSession' : IDL.Func([IDL.Text, StudentId], [], []),
  'restoreStudentProfileWithSession' : IDL.Func([IDL.Text, StudentId], [], []),
  'listArchivedStudentProfilesWithSession' : IDL.Func([IDL.Text], [IDL.Vec(StudentProfile)], ['query']),
  'deleteUserAccount' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getActivityRecords' : IDL.Func(
      [StudentId],
      [IDL.Vec(ActivityRecord)],
      ['query'],
    ),
  'getActivityRecordsWithSession' : IDL.Func(
      [IDL.Text, StudentId],
      [IDL.Vec(ActivityRecord)],
      ['query'],
    ),
  'getAllRecordsForStudent' : IDL.Func(
      [StudentId],
      [
        IDL.Record({
          'marks' : IDL.Vec(SubjectMarks),
          'reportCards' : IDL.Vec(ReportCard),
          'activities' : IDL.Vec(ActivityRecord),
          'attendance' : IDL.Vec(MonthlyAttendance),
          'sports' : IDL.Vec(SportsRecord),
          'profile' : StudentProfile,
        }),
      ],
      ['query'],
    ),
  'getAllRecordsForStudentWithSession' : IDL.Func(
      [IDL.Text, StudentId],
      [
        IDL.Record({
          'marks' : IDL.Vec(SubjectMarks),
          'reportCards' : IDL.Vec(ReportCard),
          'activities' : IDL.Vec(ActivityRecord),
          'attendance' : IDL.Vec(MonthlyAttendance),
          'sports' : IDL.Vec(SportsRecord),
          'profile' : StudentProfile,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMonthlyAttendance' : IDL.Func(
      [StudentId],
      [IDL.Vec(MonthlyAttendance)],
      ['query'],
    ),
  'getMonthlyAttendanceWithSession' : IDL.Func(
      [IDL.Text, StudentId],
      [IDL.Vec(MonthlyAttendance)],
      ['query'],
    ),
  'getReportCards' : IDL.Func([StudentId], [IDL.Vec(ReportCard)], ['query']),
  'getReportCardsWithSession' : IDL.Func(
      [IDL.Text, StudentId],
      [IDL.Vec(ReportCard)],
      ['query'],
    ),
  'getSportsRecords' : IDL.Func(
      [StudentId],
      [IDL.Vec(SportsRecord)],
      ['query'],
    ),
  'getSportsRecordsWithSession' : IDL.Func(
      [IDL.Text, StudentId],
      [IDL.Vec(SportsRecord)],
      ['query'],
    ),
  'getStudentProfile' : IDL.Func([StudentId], [StudentProfile], ['query']),
  'getStudentProfileWithSession' : IDL.Func(
      [IDL.Text, StudentId],
      [StudentProfile],
      ['query'],
    ),
  'getStudentsByClass' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(StudentProfile)],
      ['query'],
    ),
  'getStudentsByClassWithSession' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(StudentProfile)],
      ['query'],
    ),
  'getStudyMaterial' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(StudyMaterial)],
      ['query'],
    ),
  'getStudyMaterialWithSession' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(StudyMaterial)],
      ['query'],
    ),
  'getSubjectMarks' : IDL.Func([StudentId], [IDL.Vec(SubjectMarks)], ['query']),
  'getSubjectMarksWithSession' : IDL.Func(
      [IDL.Text, StudentId],
      [IDL.Vec(SubjectMarks)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllStudentProfiles' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'listAllStudentProfilesWithSession' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudentProfile)],
      ['query'],
    ),
  'listAllStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
  'listCirculars' : IDL.Func([IDL.Text], [IDL.Vec(Circular)], ['query']),
  'listClassStudyMaterials' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ClassStudyMaterial)],
      ['query'],
    ),
  'listClassStudyMaterialsByClass' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(ClassStudyMaterial)],
      ['query'],
    ),
  'listNotices' : IDL.Func([IDL.Text], [IDL.Vec(NoticePost)], ['query']),
  'listUserAccounts' : IDL.Func([IDL.Text], [IDL.Vec(UserAccount)], ['query']),
  'loginUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'displayName' : IDL.Text,
            'role' : IDL.Text,
            'assignedClass' : IDL.Opt(IDL.Nat),
            'sessionToken' : IDL.Text,
          })
        ),
      ],
      [],
    ),
  'logoutUser' : IDL.Func([IDL.Text], [], []),
  'postNotice' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'saveActivityRecord' : IDL.Func([StudentId, ActivityRecord], [], []),
  'saveActivityRecordWithSession' : IDL.Func(
      [IDL.Text, StudentId, ActivityRecord],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMonthlyAttendance' : IDL.Func([StudentId, MonthlyAttendance], [], []),
  'saveMonthlyAttendanceWithSession' : IDL.Func(
      [IDL.Text, StudentId, MonthlyAttendance],
      [],
      [],
    ),
  'saveReportCard' : IDL.Func([StudentId, ReportCard], [], []),
  'saveReportCardWithSession' : IDL.Func(
      [IDL.Text, StudentId, ReportCard],
      [],
      [],
    ),
  'saveSportsRecord' : IDL.Func([StudentId, SportsRecord], [], []),
  'saveSportsRecordWithSession' : IDL.Func(
      [IDL.Text, StudentId, SportsRecord],
      [],
      [],
    ),
  'saveStudentProfile' : IDL.Func([StudentProfile], [], []),
  'saveStudentProfileWithSession' : IDL.Func(
      [IDL.Text, StudentProfile],
      [],
      [],
    ),
  'saveSubjectMarks' : IDL.Func([StudentId, IDL.Vec(SubjectMarks)], [], []),
  'saveSubjectMarksWithSession' : IDL.Func(
      [IDL.Text, StudentId, IDL.Vec(SubjectMarks)],
      [],
      [],
    ),
  'searchStudents' : IDL.Func([IDL.Text], [IDL.Vec(StudentProfile)], ['query']),
  'searchStudentsWithSession' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(StudentProfile)],
      ['query'],
    ),
  'setStudentIdForUserProfile' : IDL.Func([IDL.Text], [], []),
  'deleteSportsRecordWithSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteActivityRecordWithSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateSportsRecordWithSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, SportsRecord], [], []),
  'updateActivityRecordWithSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, ActivityRecord], [], []),
  'updateUserPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'uploadCircular' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'uploadClassStudyMaterial' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'uploadStudyMaterial' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [],
      [],
    ),
  'uploadStudyMaterialWithSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [],
      [],
    ),
  'validateSession' : IDL.Func([IDL.Text], [IDL.Opt(SessionInfo)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserAccount = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'password' : IDL.Text,
    'role' : IDL.Text,
    'assignedClass' : IDL.Opt(IDL.Nat),
  });
  const StudentId = IDL.Text;
  const ActivityRecord = IDL.Record({
    'activityType' : IDL.Text,
    'studentId' : StudentId,
    'description' : IDL.Text,
    'session' : IDL.Text,
    'grade' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const LowerClassMarks = IDL.Record({
    'totalMarks' : IDL.Float64,
    'subjectName' : IDL.Text,
    'writtenTest1' : IDL.Float64,
    'writtenTest2' : IDL.Float64,
    'writtenTest3' : IDL.Float64,
    'writtenTest4' : IDL.Float64,
    'grade' : IDL.Text,
    'comprehensiveTest1' : IDL.Float64,
    'comprehensiveTest2' : IDL.Float64,
    'comprehensiveTest3' : IDL.Float64,
    'comprehensiveTest4' : IDL.Float64,
    'percentage' : IDL.Float64,
  });
  const UpperClassMarks = IDL.Record({
    'nb1' : IDL.Float64,
    'nb2' : IDL.Float64,
    'pt1' : IDL.Float64,
    'pt2' : IDL.Float64,
    'se1' : IDL.Float64,
    'se2' : IDL.Float64,
    'term2Total' : IDL.Float64,
    'subjectName' : IDL.Text,
    'term2Exam' : IDL.Float64,
    'finalPercentage' : IDL.Float64,
    'pt2Weightage' : IDL.Float64,
    'grade' : IDL.Text,
    'pt1Weightage' : IDL.Float64,
    'term1Exam' : IDL.Float64,
    'term1Total' : IDL.Float64,
  });
  const SubjectMarks = IDL.Variant({
    'lowerClass' : LowerClassMarks,
    'upperClass' : UpperClassMarks,
  });
  const ReportCard = IDL.Record({
    'studentId' : StudentId,
    'term2Total' : IDL.Float64,
    'behaviour' : IDL.Text,
    'rank' : IDL.Text,
    'finalPercentage' : IDL.Float64,
    'session' : IDL.Text,
    'sportsRemarks' : IDL.Text,
    'grade' : IDL.Text,
    'attendanceSummary' : IDL.Text,
    'term1Total' : IDL.Float64,
    'remarks' : IDL.Text,
  });
  const MonthlyAttendance = IDL.Record({
    'month' : IDL.Text,
    'studentId' : StudentId,
    'present' : IDL.Nat,
    'totalDays' : IDL.Nat,
    'session' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const SportsRecord = IDL.Record({
    'studentId' : StudentId,
    'game' : IDL.Text,
    'level' : IDL.Text,
    'event' : IDL.Text,
    'entryId' : IDL.Text,
    'session' : IDL.Text,
    'position' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const StudentProfile = IDL.Record({
    'pen' : IDL.Text,
    'tribe' : IDL.Text,
    'contact' : IDL.Text,
    'studentId' : StudentId,
    'dateOfBirth' : IDL.Text,
    'heightReopening' : IDL.Float64,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'motherName' : IDL.Text,
    'heightClosure' : IDL.Float64,
    'weightClosure' : IDL.Float64,
    'session' : IDL.Text,
    'fatherName' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Text,
    'classLevel' : IDL.Nat,
    'rollNo' : IDL.Text,
    'religion' : IDL.Text,
    'aadhar' : IDL.Text,
    'weightReopening' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'studentId' : IDL.Opt(StudentId),
    'name' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StudyMaterial = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'comments' : IDL.Text,
    'uploadedBy' : IDL.Principal,
  });
  const Circular = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'fileBlob' : ExternalBlob,
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'uploadedAt' : IDL.Text,
    'uploadedBy' : IDL.Text,
  });
  const ClassStudyMaterial = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'fileBlob' : ExternalBlob,
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'classLevel' : IDL.Nat,
    'uploadedAt' : IDL.Text,
    'uploadedBy' : IDL.Text,
  });
  const NoticePost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'hasFile' : IDL.Bool,
    'postedAt' : IDL.Text,
    'postedBy' : IDL.Text,
    'content' : IDL.Text,
    'fileBlob' : IDL.Opt(ExternalBlob),
    'fileName' : IDL.Text,
  });
  const SessionInfo = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'role' : IDL.Text,
    'assignedClass' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUserAccount' : IDL.Func([IDL.Text, UserAccount], [], []),
    'deleteCircular' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteClassStudyMaterial' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteNotice' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteStudentProfileWithSession' : IDL.Func([IDL.Text, StudentId], [], []),
    'archiveStudentProfileWithSession' : IDL.Func([IDL.Text, StudentId], [], []),
    'restoreStudentProfileWithSession' : IDL.Func([IDL.Text, StudentId], [], []),
    'listArchivedStudentProfilesWithSession' : IDL.Func([IDL.Text], [IDL.Vec(StudentProfile)], ['query']),
    'deleteUserAccount' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getActivityRecords' : IDL.Func(
        [StudentId],
        [IDL.Vec(ActivityRecord)],
        ['query'],
      ),
    'getActivityRecordsWithSession' : IDL.Func(
        [IDL.Text, StudentId],
        [IDL.Vec(ActivityRecord)],
        ['query'],
      ),
    'getAllRecordsForStudent' : IDL.Func(
        [StudentId],
        [
          IDL.Record({
            'marks' : IDL.Vec(SubjectMarks),
            'reportCards' : IDL.Vec(ReportCard),
            'activities' : IDL.Vec(ActivityRecord),
            'attendance' : IDL.Vec(MonthlyAttendance),
            'sports' : IDL.Vec(SportsRecord),
            'profile' : StudentProfile,
          }),
        ],
        ['query'],
      ),
    'getAllRecordsForStudentWithSession' : IDL.Func(
        [IDL.Text, StudentId],
        [
          IDL.Record({
            'marks' : IDL.Vec(SubjectMarks),
            'reportCards' : IDL.Vec(ReportCard),
            'activities' : IDL.Vec(ActivityRecord),
            'attendance' : IDL.Vec(MonthlyAttendance),
            'sports' : IDL.Vec(SportsRecord),
            'profile' : StudentProfile,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMonthlyAttendance' : IDL.Func(
        [StudentId],
        [IDL.Vec(MonthlyAttendance)],
        ['query'],
      ),
    'getMonthlyAttendanceWithSession' : IDL.Func(
        [IDL.Text, StudentId],
        [IDL.Vec(MonthlyAttendance)],
        ['query'],
      ),
    'getReportCards' : IDL.Func([StudentId], [IDL.Vec(ReportCard)], ['query']),
    'getReportCardsWithSession' : IDL.Func(
        [IDL.Text, StudentId],
        [IDL.Vec(ReportCard)],
        ['query'],
      ),
    'getSportsRecords' : IDL.Func(
        [StudentId],
        [IDL.Vec(SportsRecord)],
        ['query'],
      ),
    'getSportsRecordsWithSession' : IDL.Func(
        [IDL.Text, StudentId],
        [IDL.Vec(SportsRecord)],
        ['query'],
      ),
    'getStudentProfile' : IDL.Func([StudentId], [StudentProfile], ['query']),
    'getStudentProfileWithSession' : IDL.Func(
        [IDL.Text, StudentId],
        [StudentProfile],
        ['query'],
      ),
    'getStudentsByClass' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'getStudentsByClassWithSession' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'getStudyMaterial' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StudyMaterial)],
        ['query'],
      ),
    'getStudyMaterialWithSession' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(StudyMaterial)],
        ['query'],
      ),
    'getSubjectMarks' : IDL.Func(
        [StudentId],
        [IDL.Vec(SubjectMarks)],
        ['query'],
      ),
    'getSubjectMarksWithSession' : IDL.Func(
        [IDL.Text, StudentId],
        [IDL.Vec(SubjectMarks)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllStudentProfiles' : IDL.Func(
        [],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'listAllStudentProfilesWithSession' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'listAllStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
    'listCirculars' : IDL.Func([IDL.Text], [IDL.Vec(Circular)], ['query']),
    'listClassStudyMaterials' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ClassStudyMaterial)],
        ['query'],
      ),
    'listClassStudyMaterialsByClass' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(ClassStudyMaterial)],
        ['query'],
      ),
    'listNotices' : IDL.Func([IDL.Text], [IDL.Vec(NoticePost)], ['query']),
    'listUserAccounts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserAccount)],
        ['query'],
      ),
    'loginUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'displayName' : IDL.Text,
              'role' : IDL.Text,
              'assignedClass' : IDL.Opt(IDL.Nat),
              'sessionToken' : IDL.Text,
            })
          ),
        ],
        [],
      ),
    'logoutUser' : IDL.Func([IDL.Text], [], []),
    'postNotice' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'saveActivityRecord' : IDL.Func([StudentId, ActivityRecord], [], []),
    'saveActivityRecordWithSession' : IDL.Func(
        [IDL.Text, StudentId, ActivityRecord],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMonthlyAttendance' : IDL.Func([StudentId, MonthlyAttendance], [], []),
    'saveMonthlyAttendanceWithSession' : IDL.Func(
        [IDL.Text, StudentId, MonthlyAttendance],
        [],
        [],
      ),
    'saveReportCard' : IDL.Func([StudentId, ReportCard], [], []),
    'saveReportCardWithSession' : IDL.Func(
        [IDL.Text, StudentId, ReportCard],
        [],
        [],
      ),
    'saveSportsRecord' : IDL.Func([StudentId, SportsRecord], [], []),
    'saveSportsRecordWithSession' : IDL.Func(
        [IDL.Text, StudentId, SportsRecord],
        [],
        [],
      ),
    'saveStudentProfile' : IDL.Func([StudentProfile], [], []),
    'saveStudentProfileWithSession' : IDL.Func(
        [IDL.Text, StudentProfile],
        [],
        [],
      ),
    'saveSubjectMarks' : IDL.Func([StudentId, IDL.Vec(SubjectMarks)], [], []),
    'saveSubjectMarksWithSession' : IDL.Func(
        [IDL.Text, StudentId, IDL.Vec(SubjectMarks)],
        [],
        [],
      ),
    'searchStudents' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'searchStudentsWithSession' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'setStudentIdForUserProfile' : IDL.Func([IDL.Text], [], []),
    'deleteSportsRecordWithSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteActivityRecordWithSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'updateSportsRecordWithSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, SportsRecord], [], []),
    'updateActivityRecordWithSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, ActivityRecord], [], []),
    'updateUserPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'uploadCircular' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'uploadClassStudyMaterial' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'uploadStudyMaterial' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [],
        [],
      ),
    'uploadStudyMaterialWithSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [],
        [],
      ),
    'validateSession' : IDL.Func([IDL.Text], [IDL.Opt(SessionInfo)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };