/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityRecord {
  'activityType' : string,
  'studentId' : StudentId,
  'description' : string,
  'session' : string,
  'grade' : string,
  'remarks' : string,
}
export interface Circular {
  'id' : string,
  'title' : string,
  'fileBlob' : ExternalBlob,
  'description' : string,
  'fileName' : string,
  'uploadedAt' : string,
  'uploadedBy' : string,
}
export interface ClassStudyMaterial {
  'id' : string,
  'title' : string,
  'subject' : string,
  'fileBlob' : ExternalBlob,
  'description' : string,
  'fileName' : string,
  'classLevel' : bigint,
  'uploadedAt' : string,
  'uploadedBy' : string,
}
export type ExternalBlob = Uint8Array;
export interface LowerClassMarks {
  'totalMarks' : number,
  'subjectName' : string,
  'writtenTest1' : number,
  'writtenTest2' : number,
  'writtenTest3' : number,
  'writtenTest4' : number,
  'grade' : string,
  'comprehensiveTest1' : number,
  'comprehensiveTest2' : number,
  'comprehensiveTest3' : number,
  'comprehensiveTest4' : number,
  'percentage' : number,
}
export interface MonthlyAttendance {
  'month' : string,
  'studentId' : StudentId,
  'present' : bigint,
  'totalDays' : bigint,
  'session' : string,
  'percentage' : number,
}
export interface NoticePost {
  'id' : string,
  'title' : string,
  'hasFile' : boolean,
  'postedAt' : string,
  'postedBy' : string,
  'content' : string,
  'fileBlob' : [] | [ExternalBlob],
  'fileName' : string,
}
export interface ReportCard {
  'studentId' : StudentId,
  'term2Total' : number,
  'behaviour' : string,
  'rank' : string,
  'finalPercentage' : number,
  'session' : string,
  'sportsRemarks' : string,
  'grade' : string,
  'attendanceSummary' : string,
  'term1Total' : number,
  'remarks' : string,
}
export interface SessionInfo {
  'username' : string,
  'displayName' : string,
  'role' : string,
  'assignedClass' : [] | [bigint],
}
export interface SportsRecord {
  'studentId' : StudentId,
  'game' : string,
  'level' : string,
  'event' : string,
  'entryId' : string,
  'session' : string,
  'position' : string,
  'remarks' : string,
}
export type StudentId = string;
export interface StudentProfile {
  'pen' : string,
  'tribe' : string,
  'contact' : string,
  'studentId' : StudentId,
  'dateOfBirth' : string,
  'heightReopening' : number,
  'name' : string,
  'section' : string,
  'motherName' : string,
  'heightClosure' : number,
  'weightClosure' : number,
  'session' : string,
  'fatherName' : string,
  'bloodGroup' : [] | [string],
  'address' : string,
  'gender' : string,
  'classLevel' : bigint,
  'rollNo' : string,
  'religion' : string,
  'aadhar' : string,
  'weightReopening' : number,
}
export interface StudyMaterial {
  'id' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'comments' : string,
  'uploadedBy' : Principal,
}
export type SubjectMarks = { 'lowerClass' : LowerClassMarks } |
  { 'upperClass' : UpperClassMarks };
export type TeacherId = string;
export interface TeacherMonthlyAttendance {
  'month' : string,
  'present' : bigint,
  'casualLeave' : bigint,
  'session' : string,
  'teacherId' : TeacherId,
  'totalWorkingDays' : bigint,
  'extraordinaryLeave' : bigint,
}
export interface TeacherProfile {
  'contact' : string,
  'subject' : string,
  'dateOfBirth' : string,
  'name' : string,
  'designation' : string,
  'joiningDate' : string,
  'photoUrl' : string,
  'email' : string,
  'address' : string,
  'gender' : string,
  'teacherId' : TeacherId,
}
export interface UpperClassMarks {
  'nb1' : number,
  'nb2' : number,
  'pt1' : number,
  'pt2' : number,
  'se1' : number,
  'se2' : number,
  'term2Total' : number,
  'subjectName' : string,
  'term2Exam' : number,
  'finalPercentage' : number,
  'pt2Weightage' : number,
  'grade' : string,
  'pt1Weightage' : number,
  'term1Exam' : number,
  'term1Total' : number,
}
export interface UserAccount {
  'username' : string,
  'displayName' : string,
  'password' : string,
  'role' : string,
  'assignedClass' : [] | [bigint],
}
export interface UserProfile { 'studentId' : [] | [StudentId], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'archiveStudentProfileWithSession' : ActorMethod<
    [string, StudentId],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUserAccount' : ActorMethod<[string, UserAccount], undefined>,
  'deleteActivityRecordWithSession' : ActorMethod<
    [string, StudentId, bigint],
    undefined
  >,
  'deleteAttendanceRecordWithSession' : ActorMethod<
    [string, StudentId, string, string],
    undefined
  >,
  'deleteCircular' : ActorMethod<[string, string], undefined>,
  'deleteClassStudyMaterial' : ActorMethod<[string, string], undefined>,
  'deleteNotice' : ActorMethod<[string, string], undefined>,
  'deleteSportsRecordWithSession' : ActorMethod<
    [string, StudentId, string],
    undefined
  >,
  'deleteStudentProfileWithSession' : ActorMethod<
    [string, StudentId],
    undefined
  >,
  'deleteTeacherProfileWithSession' : ActorMethod<
    [string, TeacherId],
    undefined
  >,
  'deleteUserAccount' : ActorMethod<[string, string], undefined>,
  'getActivityRecords' : ActorMethod<[StudentId], Array<ActivityRecord>>,
  'getActivityRecordsWithSession' : ActorMethod<
    [string, StudentId],
    Array<ActivityRecord>
  >,
  'getAllRecordsForStudent' : ActorMethod<
    [StudentId],
    {
      'marks' : Array<SubjectMarks>,
      'reportCards' : Array<ReportCard>,
      'activities' : Array<ActivityRecord>,
      'attendance' : Array<MonthlyAttendance>,
      'sports' : Array<SportsRecord>,
      'profile' : StudentProfile,
    }
  >,
  'getAllRecordsForStudentWithSession' : ActorMethod<
    [string, StudentId],
    {
      'marks' : Array<SubjectMarks>,
      'reportCards' : Array<ReportCard>,
      'activities' : Array<ActivityRecord>,
      'attendance' : Array<MonthlyAttendance>,
      'sports' : Array<SportsRecord>,
      'profile' : StudentProfile,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentAppSession' : ActorMethod<[], string>,
  'getMonthlyAttendance' : ActorMethod<[StudentId], Array<MonthlyAttendance>>,
  'getMonthlyAttendanceWithSession' : ActorMethod<
    [string, StudentId],
    Array<MonthlyAttendance>
  >,
  'getReportCards' : ActorMethod<[StudentId], Array<ReportCard>>,
  'getReportCardsWithSession' : ActorMethod<
    [string, StudentId],
    Array<ReportCard>
  >,
  'getSportsRecords' : ActorMethod<[StudentId], Array<SportsRecord>>,
  'getSportsRecordsWithSession' : ActorMethod<
    [string, StudentId],
    Array<SportsRecord>
  >,
  'getStudentProfile' : ActorMethod<[StudentId], StudentProfile>,
  'getStudentProfileWithSession' : ActorMethod<
    [string, StudentId],
    StudentProfile
  >,
  'getStudentSessionListWithSession' : ActorMethod<
    [string, StudentId],
    Array<string>
  >,
  'getStudentsByClass' : ActorMethod<[bigint], Array<StudentProfile>>,
  'getStudentsByClassWithSession' : ActorMethod<
    [string, bigint],
    Array<StudentProfile>
  >,
  'getStudyMaterial' : ActorMethod<[string], [] | [StudyMaterial]>,
  'getStudyMaterialWithSession' : ActorMethod<
    [string, string],
    [] | [StudyMaterial]
  >,
  'getSubjectMarks' : ActorMethod<[StudentId], Array<SubjectMarks>>,
  'getSubjectMarksForSessionWithSession' : ActorMethod<
    [string, StudentId, string],
    Array<SubjectMarks>
  >,
  'getSubjectMarksWithSession' : ActorMethod<
    [string, StudentId],
    Array<SubjectMarks>
  >,
  'getTeacherAttendanceWithSession' : ActorMethod<
    [string, TeacherId, string],
    Array<TeacherMonthlyAttendance>
  >,
  'getTeacherProfileWithSession' : ActorMethod<
    [string, TeacherId],
    TeacherProfile
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllStudentProfiles' : ActorMethod<[], Array<StudentProfile>>,
  'listAllStudentProfilesWithSession' : ActorMethod<
    [string],
    Array<StudentProfile>
  >,
  'listAllStudyMaterials' : ActorMethod<[], Array<StudyMaterial>>,
  'listAllTeacherProfilesWithSession' : ActorMethod<
    [string],
    Array<TeacherProfile>
  >,
  'listArchivedStudentProfilesWithSession' : ActorMethod<
    [string],
    Array<StudentProfile>
  >,
  'listCirculars' : ActorMethod<[string], Array<Circular>>,
  'listClassStudyMaterials' : ActorMethod<[string], Array<ClassStudyMaterial>>,
  'listClassStudyMaterialsByClass' : ActorMethod<
    [string, bigint],
    Array<ClassStudyMaterial>
  >,
  'listNotices' : ActorMethod<[string], Array<NoticePost>>,
  'listUserAccounts' : ActorMethod<[string], Array<UserAccount>>,
  'loginUser' : ActorMethod<
    [string, string],
    [] | [
      {
        'displayName' : string,
        'role' : string,
        'assignedClass' : [] | [bigint],
        'sessionToken' : string,
      }
    ]
  >,
  'logoutUser' : ActorMethod<[string], undefined>,
  'postNotice' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      boolean,
      [] | [ExternalBlob],
      string,
      string,
    ],
    undefined
  >,
  'promoteStudentWithSession' : ActorMethod<
    [string, StudentId, bigint, string],
    undefined
  >,
  'restoreStudentProfileWithSession' : ActorMethod<
    [string, StudentId],
    undefined
  >,
  'saveActivityRecord' : ActorMethod<[StudentId, ActivityRecord], undefined>,
  'saveActivityRecordWithSession' : ActorMethod<
    [string, StudentId, ActivityRecord],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMonthlyAttendance' : ActorMethod<
    [StudentId, MonthlyAttendance],
    undefined
  >,
  'saveMonthlyAttendanceWithSession' : ActorMethod<
    [string, StudentId, MonthlyAttendance],
    undefined
  >,
  'saveReportCard' : ActorMethod<[StudentId, ReportCard], undefined>,
  'saveReportCardWithSession' : ActorMethod<
    [string, StudentId, ReportCard],
    undefined
  >,
  'saveSportsRecord' : ActorMethod<[StudentId, SportsRecord], undefined>,
  'saveSportsRecordWithSession' : ActorMethod<
    [string, StudentId, SportsRecord],
    undefined
  >,
  'saveStudentProfile' : ActorMethod<[StudentProfile], undefined>,
  'saveStudentProfileWithSession' : ActorMethod<
    [string, StudentProfile],
    undefined
  >,
  'saveSubjectMarks' : ActorMethod<[StudentId, Array<SubjectMarks>], undefined>,
  'saveSubjectMarksForSessionWithSession' : ActorMethod<
    [string, StudentId, string, Array<SubjectMarks>],
    undefined
  >,
  'saveSubjectMarksWithSession' : ActorMethod<
    [string, StudentId, Array<SubjectMarks>],
    undefined
  >,
  'saveTeacherAttendanceWithSession' : ActorMethod<
    [string, TeacherMonthlyAttendance],
    undefined
  >,
  'saveTeacherProfileWithSession' : ActorMethod<
    [string, TeacherProfile],
    undefined
  >,
  'searchStudents' : ActorMethod<[string], Array<StudentProfile>>,
  'searchStudentsWithSession' : ActorMethod<
    [string, string],
    Array<StudentProfile>
  >,
  'setCurrentAppSessionWithSession' : ActorMethod<[string, string], undefined>,
  'setStudentIdForUserProfile' : ActorMethod<[string], undefined>,
  'updateActivityRecordWithSession' : ActorMethod<
    [string, StudentId, bigint, ActivityRecord],
    undefined
  >,
  'updateSportsRecordWithSession' : ActorMethod<
    [string, StudentId, string, SportsRecord],
    undefined
  >,
  'updateUserPassword' : ActorMethod<[string, string, string], undefined>,
  'uploadCircular' : ActorMethod<
    [string, string, string, string, ExternalBlob, string, string],
    undefined
  >,
  'uploadClassStudyMaterial' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      string,
      ExternalBlob,
      string,
      string,
    ],
    undefined
  >,
  'uploadStudyMaterial' : ActorMethod<
    [string, string, ExternalBlob, string],
    undefined
  >,
  'uploadStudyMaterialWithSession' : ActorMethod<
    [string, string, string, ExternalBlob, string],
    undefined
  >,
  'validateSession' : ActorMethod<[string], [] | [SessionInfo]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];