/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface LowerClassMarks {
    totalMarks: number;
    subjectName: string;
    writtenTest1: number;
    writtenTest2: number;
    writtenTest3: number;
    writtenTest4: number;
    grade: string;
    comprehensiveTest1: number;
    comprehensiveTest2: number;
    comprehensiveTest3: number;
    comprehensiveTest4: number;
    percentage: number;
}
export interface ReportCard {
    studentId: StudentId;
    term2Total: number;
    behaviour: string;
    rank: string;
    finalPercentage: number;
    session: string;
    sportsRemarks: string;
    grade: string;
    attendanceSummary: string;
    term1Total: number;
    remarks: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface SportsRecord {
    studentId: StudentId;
    game: string;
    level: string;
    event: string;
    entryId: string;
    session: string;
    position: string;
    remarks: string;
}
export interface NoticePost {
    id: string;
    title: string;
    hasFile: boolean;
    postedAt: string;
    postedBy: string;
    content: string;
    fileBlob?: ExternalBlob;
    fileName: string;
}
export interface UserAccount {
    username: string;
    displayName: string;
    password: string;
    role: string;
    assignedClass?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type StudentId = string;
export type TeacherId = string;
export interface TeacherProfile {
    contact: string;
    subject: string;
    dateOfBirth: string;
    name: string;
    designation: string;
    joiningDate: string;
    photoUrl: string;
    email: string;
    address: string;
    gender: string;
    teacherId: TeacherId;
}
export interface MonthlyAttendance {
    month: string;
    studentId: StudentId;
    present: bigint;
    totalDays: bigint;
    session: string;
    percentage: number;
}
export type SubjectMarks = {
    __kind__: "lowerClass";
    lowerClass: LowerClassMarks;
} | {
    __kind__: "upperClass";
    upperClass: UpperClassMarks;
};
export interface StudentProfile {
    pen: string;
    tribe: string;
    contact: string;
    studentId: StudentId;
    dateOfBirth: string;
    heightReopening: number;
    name: string;
    section: string;
    motherName: string;
    heightClosure: number;
    weightClosure: number;
    session: string;
    fatherName: string;
    bloodGroup?: string;
    address: string;
    gender: string;
    classLevel: bigint;
    rollNo: string;
    religion: string;
    aadhar: string;
    weightReopening: number;
}
export interface SessionInfo {
    username: string;
    displayName: string;
    role: string;
    assignedClass?: bigint;
}
export interface Circular {
    id: string;
    title: string;
    fileBlob: ExternalBlob;
    description: string;
    fileName: string;
    uploadedAt: string;
    uploadedBy: string;
}
export interface UpperClassMarks {
    nb1: number;
    nb2: number;
    pt1: number;
    pt2: number;
    se1: number;
    se2: number;
    term2Total: number;
    subjectName: string;
    term2Exam: number;
    finalPercentage: number;
    pt2Weightage: number;
    grade: string;
    pt1Weightage: number;
    term1Exam: number;
    term1Total: number;
}
export interface StudyMaterial {
    id: string;
    blob: ExternalBlob;
    name: string;
    comments: string;
    uploadedBy: Principal;
}
export interface ActivityRecord {
    activityType: string;
    studentId: StudentId;
    description: string;
    session: string;
    grade: string;
    remarks: string;
}
export interface ClassStudyMaterial {
    id: string;
    title: string;
    subject: string;
    fileBlob: ExternalBlob;
    description: string;
    fileName: string;
    classLevel: bigint;
    uploadedAt: string;
    uploadedBy: string;
}
export interface UserProfile {
    studentId?: StudentId;
    name: string;
}
export interface TeacherMonthlyAttendance {
    month: string;
    present: bigint;
    casualLeave: bigint;
    session: string;
    teacherId: TeacherId;
    totalWorkingDays: bigint;
    extraordinaryLeave: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    archiveStudentProfileWithSession(sessionToken: string, studentId: StudentId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createUserAccount(sessionToken: string, account: UserAccount): Promise<void>;
    deleteActivityRecordWithSession(sessionToken: string, studentId: StudentId, index: bigint): Promise<void>;
    deleteAttendanceRecordWithSession(sessionToken: string, studentId: StudentId, month: string, session: string): Promise<void>;
    deleteCircular(sessionToken: string, id: string): Promise<void>;
    deleteClassStudyMaterial(sessionToken: string, id: string): Promise<void>;
    deleteNotice(sessionToken: string, id: string): Promise<void>;
    deleteSportsRecordWithSession(sessionToken: string, studentId: StudentId, entryId: string): Promise<void>;
    deleteStudentProfileWithSession(sessionToken: string, studentId: StudentId): Promise<void>;
    deleteTeacherProfileWithSession(sessionToken: string, teacherId: TeacherId): Promise<void>;
    deleteUserAccount(sessionToken: string, username: string): Promise<void>;
    getActivityRecords(studentId: StudentId): Promise<Array<ActivityRecord>>;
    getActivityRecordsWithSession(sessionToken: string, studentId: StudentId): Promise<Array<ActivityRecord>>;
    getAllRecordsForStudent(studentId: StudentId): Promise<{
        marks: Array<SubjectMarks>;
        reportCards: Array<ReportCard>;
        activities: Array<ActivityRecord>;
        attendance: Array<MonthlyAttendance>;
        sports: Array<SportsRecord>;
        profile: StudentProfile;
    }>;
    getAllRecordsForStudentWithSession(sessionToken: string, studentId: StudentId): Promise<{
        marks: Array<SubjectMarks>;
        reportCards: Array<ReportCard>;
        activities: Array<ActivityRecord>;
        attendance: Array<MonthlyAttendance>;
        sports: Array<SportsRecord>;
        profile: StudentProfile;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentAppSession(): Promise<string>;
    getMonthlyAttendance(studentId: StudentId): Promise<Array<MonthlyAttendance>>;
    getMonthlyAttendanceWithSession(sessionToken: string, studentId: StudentId): Promise<Array<MonthlyAttendance>>;
    getReportCards(studentId: StudentId): Promise<Array<ReportCard>>;
    getReportCardsWithSession(sessionToken: string, studentId: StudentId): Promise<Array<ReportCard>>;
    getSportsRecords(studentId: StudentId): Promise<Array<SportsRecord>>;
    getSportsRecordsWithSession(sessionToken: string, studentId: StudentId): Promise<Array<SportsRecord>>;
    getStudentProfile(studentId: StudentId): Promise<StudentProfile>;
    getStudentProfileWithSession(sessionToken: string, studentId: StudentId): Promise<StudentProfile>;
    getStudentSessionListWithSession(sessionToken: string, studentId: StudentId): Promise<Array<string>>;
    getStudentsByClass(classLevel: bigint): Promise<Array<StudentProfile>>;
    getStudentsByClassWithSession(sessionToken: string, classLevel: bigint): Promise<Array<StudentProfile>>;
    getStudyMaterial(id: string): Promise<StudyMaterial | null>;
    getStudyMaterialWithSession(sessionToken: string, id: string): Promise<StudyMaterial | null>;
    getSubjectMarks(studentId: StudentId): Promise<Array<SubjectMarks>>;
    getSubjectMarksForSessionWithSession(sessionToken: string, studentId: StudentId, session: string): Promise<Array<SubjectMarks>>;
    getSubjectMarksWithSession(sessionToken: string, studentId: StudentId): Promise<Array<SubjectMarks>>;
    getTeacherAttendanceWithSession(sessionToken: string, teacherId: TeacherId, session: string): Promise<Array<TeacherMonthlyAttendance>>;
    getTeacherProfileWithSession(sessionToken: string, teacherId: TeacherId): Promise<TeacherProfile>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllStudentProfiles(): Promise<Array<StudentProfile>>;
    listAllStudentProfilesWithSession(sessionToken: string): Promise<Array<StudentProfile>>;
    listAllStudyMaterials(): Promise<Array<StudyMaterial>>;
    listAllTeacherProfilesWithSession(sessionToken: string): Promise<Array<TeacherProfile>>;
    listArchivedStudentProfilesWithSession(sessionToken: string): Promise<Array<StudentProfile>>;
    listCirculars(sessionToken: string): Promise<Array<Circular>>;
    listClassStudyMaterials(sessionToken: string): Promise<Array<ClassStudyMaterial>>;
    listClassStudyMaterialsByClass(sessionToken: string, classLevel: bigint): Promise<Array<ClassStudyMaterial>>;
    listNotices(sessionToken: string): Promise<Array<NoticePost>>;
    listUserAccounts(sessionToken: string): Promise<Array<UserAccount>>;
    loginUser(username: string, password: string): Promise<{
        displayName: string;
        role: string;
        assignedClass?: bigint;
        sessionToken: string;
    } | null>;
    logoutUser(sessionToken: string): Promise<void>;
    postNotice(sessionToken: string, id: string, title: string, content: string, hasFile: boolean, fileBlob: ExternalBlob | null, fileName: string, postedAt: string): Promise<void>;
    promoteStudentWithSession(sessionToken: string, studentId: StudentId, newClassLevel: bigint, newSession: string): Promise<void>;
    restoreStudentProfileWithSession(sessionToken: string, studentId: StudentId): Promise<void>;
    saveActivityRecord(studentId: StudentId, activity: ActivityRecord): Promise<void>;
    saveActivityRecordWithSession(sessionToken: string, studentId: StudentId, activity: ActivityRecord): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveMonthlyAttendance(studentId: StudentId, attendance: MonthlyAttendance): Promise<void>;
    saveMonthlyAttendanceWithSession(sessionToken: string, studentId: StudentId, attendance: MonthlyAttendance): Promise<void>;
    saveReportCard(studentId: StudentId, report: ReportCard): Promise<void>;
    saveReportCardWithSession(sessionToken: string, studentId: StudentId, report: ReportCard): Promise<void>;
    saveSportsRecord(studentId: StudentId, record: SportsRecord): Promise<void>;
    saveSportsRecordWithSession(sessionToken: string, studentId: StudentId, record: SportsRecord): Promise<void>;
    saveStudentProfile(profile: StudentProfile): Promise<void>;
    saveStudentProfileWithSession(sessionToken: string, profile: StudentProfile): Promise<void>;
    saveSubjectMarks(studentId: StudentId, marks: Array<SubjectMarks>): Promise<void>;
    saveSubjectMarksForSessionWithSession(sessionToken: string, studentId: StudentId, session: string, marks: Array<SubjectMarks>): Promise<void>;
    saveSubjectMarksWithSession(sessionToken: string, studentId: StudentId, marks: Array<SubjectMarks>): Promise<void>;
    saveTeacherAttendanceWithSession(sessionToken: string, attendance: TeacherMonthlyAttendance): Promise<void>;
    saveTeacherProfileWithSession(sessionToken: string, profile: TeacherProfile): Promise<void>;
    searchStudents(searchTerm: string): Promise<Array<StudentProfile>>;
    searchStudentsWithSession(sessionToken: string, searchTerm: string): Promise<Array<StudentProfile>>;
    setCurrentAppSessionWithSession(sessionToken: string, session: string): Promise<void>;
    setStudentIdForUserProfile(studentId: string): Promise<void>;
    updateActivityRecordWithSession(sessionToken: string, studentId: StudentId, index: bigint, updated: ActivityRecord): Promise<void>;
    updateSportsRecordWithSession(sessionToken: string, studentId: StudentId, entryId: string, updated: SportsRecord): Promise<void>;
    updateUserPassword(sessionToken: string, username: string, newPassword: string): Promise<void>;
    uploadCircular(sessionToken: string, id: string, title: string, description: string, fileBlob: ExternalBlob, fileName: string, uploadedAt: string): Promise<void>;
    uploadClassStudyMaterial(sessionToken: string, id: string, title: string, classLevel: bigint, subject: string, description: string, fileBlob: ExternalBlob, fileName: string, uploadedAt: string): Promise<void>;
    uploadStudyMaterial(id: string, name: string, blob: ExternalBlob, comments: string): Promise<void>;
    uploadStudyMaterialWithSession(sessionToken: string, id: string, name: string, blob: ExternalBlob, comments: string): Promise<void>;
    validateSession(sessionToken: string): Promise<SessionInfo | null>;
}
import type { ActivityRecord as _ActivityRecord, Circular as _Circular, ClassStudyMaterial as _ClassStudyMaterial, ExternalBlob as _ExternalBlob, LowerClassMarks as _LowerClassMarks, MonthlyAttendance as _MonthlyAttendance, NoticePost as _NoticePost, ReportCard as _ReportCard, SessionInfo as _SessionInfo, SportsRecord as _SportsRecord, StudentId as _StudentId, StudentProfile as _StudentProfile, StudyMaterial as _StudyMaterial, SubjectMarks as _SubjectMarks, UpperClassMarks as _UpperClassMarks, UserAccount as _UserAccount, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async archiveStudentProfileWithSession(arg0: string, arg1: StudentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveStudentProfileWithSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveStudentProfileWithSession(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createUserAccount(arg0: string, arg1: UserAccount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserAccount(arg0, to_candid_UserAccount_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserAccount(arg0, to_candid_UserAccount_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteActivityRecordWithSession(arg0: string, arg1: StudentId, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivityRecordWithSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivityRecordWithSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteAttendanceRecordWithSession(arg0: string, arg1: StudentId, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAttendanceRecordWithSession(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAttendanceRecordWithSession(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteCircular(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCircular(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCircular(arg0, arg1);
            return result;
        }
    }
    async deleteClassStudyMaterial(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClassStudyMaterial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClassStudyMaterial(arg0, arg1);
            return result;
        }
    }
    async deleteNotice(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0, arg1);
            return result;
        }
    }
    async deleteSportsRecordWithSession(arg0: string, arg1: StudentId, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSportsRecordWithSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSportsRecordWithSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteStudentProfileWithSession(arg0: string, arg1: StudentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudentProfileWithSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudentProfileWithSession(arg0, arg1);
            return result;
        }
    }
    async deleteTeacherProfileWithSession(arg0: string, arg1: TeacherId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeacherProfileWithSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeacherProfileWithSession(arg0, arg1);
            return result;
        }
    }
    async deleteUserAccount(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserAccount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserAccount(arg0, arg1);
            return result;
        }
    }
    async getActivityRecords(arg0: StudentId): Promise<Array<ActivityRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityRecords(arg0);
            return result;
        }
    }
    async getActivityRecordsWithSession(arg0: string, arg1: StudentId): Promise<Array<ActivityRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityRecordsWithSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityRecordsWithSession(arg0, arg1);
            return result;
        }
    }
    async getAllRecordsForStudent(arg0: StudentId): Promise<{
        marks: Array<SubjectMarks>;
        reportCards: Array<ReportCard>;
        activities: Array<ActivityRecord>;
        attendance: Array<MonthlyAttendance>;
        sports: Array<SportsRecord>;
        profile: StudentProfile;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecordsForStudent(arg0);
                return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecordsForStudent(arg0);
            return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRecordsForStudentWithSession(arg0: string, arg1: StudentId): Promise<{
        marks: Array<SubjectMarks>;
        reportCards: Array<ReportCard>;
        activities: Array<ActivityRecord>;
        attendance: Array<MonthlyAttendance>;
        sports: Array<SportsRecord>;
        profile: StudentProfile;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecordsForStudentWithSession(arg0, arg1);
                return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecordsForStudentWithSession(arg0, arg1);
            return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentAppSession(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentAppSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentAppSession();
            return result;
        }
    }
    async getMonthlyAttendance(arg0: StudentId): Promise<Array<MonthlyAttendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyAttendance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyAttendance(arg0);
            return result;
        }
    }
    async getMonthlyAttendanceWithSession(arg0: string, arg1: StudentId): Promise<Array<MonthlyAttendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyAttendanceWithSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyAttendanceWithSession(arg0, arg1);
            return result;
        }
    }
    async getReportCards(arg0: StudentId): Promise<Array<ReportCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportCards(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportCards(arg0);
            return result;
        }
    }
    async getReportCardsWithSession(arg0: string, arg1: StudentId): Promise<Array<ReportCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportCardsWithSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportCardsWithSession(arg0, arg1);
            return result;
        }
    }
    async getSportsRecords(arg0: StudentId): Promise<Array<SportsRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSportsRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSportsRecords(arg0);
            return result;
        }
    }
    async getSportsRecordsWithSession(arg0: string, arg1: StudentId): Promise<Array<SportsRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSportsRecordsWithSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSportsRecordsWithSession(arg0, arg1);
            return result;
        }
    }
    async getStudentProfile(arg0: StudentId): Promise<StudentProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProfile(arg0);
                return from_candid_StudentProfile_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProfile(arg0);
            return from_candid_StudentProfile_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentProfileWithSession(arg0: string, arg1: StudentId): Promise<StudentProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProfileWithSession(arg0, arg1);
                return from_candid_StudentProfile_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProfileWithSession(arg0, arg1);
            return from_candid_StudentProfile_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentSessionListWithSession(arg0: string, arg1: StudentId): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentSessionListWithSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentSessionListWithSession(arg0, arg1);
            return result;
        }
    }
    async getStudentsByClass(arg0: bigint): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsByClass(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsByClass(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentsByClassWithSession(arg0: string, arg1: bigint): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsByClassWithSession(arg0, arg1);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsByClassWithSession(arg0, arg1);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudyMaterial(arg0: string): Promise<StudyMaterial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyMaterial(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyMaterial(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudyMaterialWithSession(arg0: string, arg1: string): Promise<StudyMaterial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyMaterialWithSession(arg0, arg1);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyMaterialWithSession(arg0, arg1);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubjectMarks(arg0: StudentId): Promise<Array<SubjectMarks>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectMarks(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectMarks(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubjectMarksForSessionWithSession(arg0: string, arg1: StudentId, arg2: string): Promise<Array<SubjectMarks>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectMarksForSessionWithSession(arg0, arg1, arg2);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectMarksForSessionWithSession(arg0, arg1, arg2);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubjectMarksWithSession(arg0: string, arg1: StudentId): Promise<Array<SubjectMarks>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectMarksWithSession(arg0, arg1);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectMarksWithSession(arg0, arg1);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacherAttendanceWithSession(arg0: string, arg1: TeacherId, arg2: string): Promise<Array<TeacherMonthlyAttendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherAttendanceWithSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherAttendanceWithSession(arg0, arg1, arg2);
            return result;
        }
    }
    async getTeacherProfileWithSession(arg0: string, arg1: TeacherId): Promise<TeacherProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherProfileWithSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherProfileWithSession(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllStudentProfiles(): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStudentProfiles();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStudentProfiles();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllStudentProfilesWithSession(arg0: string): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStudentProfilesWithSession(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStudentProfilesWithSession(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllStudyMaterials(): Promise<Array<StudyMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStudyMaterials();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStudyMaterials();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllTeacherProfilesWithSession(arg0: string): Promise<Array<TeacherProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllTeacherProfilesWithSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllTeacherProfilesWithSession(arg0);
            return result;
        }
    }
    async listArchivedStudentProfilesWithSession(arg0: string): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listArchivedStudentProfilesWithSession(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listArchivedStudentProfilesWithSession(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCirculars(arg0: string): Promise<Array<Circular>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCirculars(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCirculars(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async listClassStudyMaterials(arg0: string): Promise<Array<ClassStudyMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClassStudyMaterials(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClassStudyMaterials(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listClassStudyMaterialsByClass(arg0: string, arg1: bigint): Promise<Array<ClassStudyMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClassStudyMaterialsByClass(arg0, arg1);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClassStudyMaterialsByClass(arg0, arg1);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNotices(arg0: string): Promise<Array<NoticePost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotices(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotices(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUserAccounts(arg0: string): Promise<Array<UserAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUserAccounts(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUserAccounts(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<{
        displayName: string;
        role: string;
        assignedClass?: bigint;
        sessionToken: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async logoutUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutUser(arg0);
            return result;
        }
    }
    async postNotice(arg0: string, arg1: string, arg2: string, arg3: string, arg4: boolean, arg5: ExternalBlob | null, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postNotice(arg0, arg1, arg2, arg3, arg4, await to_candid_opt_n46(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postNotice(arg0, arg1, arg2, arg3, arg4, await to_candid_opt_n46(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async promoteStudentWithSession(arg0: string, arg1: StudentId, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteStudentWithSession(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteStudentWithSession(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async restoreStudentProfileWithSession(arg0: string, arg1: StudentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreStudentProfileWithSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreStudentProfileWithSession(arg0, arg1);
            return result;
        }
    }
    async saveActivityRecord(arg0: StudentId, arg1: ActivityRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveActivityRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveActivityRecord(arg0, arg1);
            return result;
        }
    }
    async saveActivityRecordWithSession(arg0: string, arg1: StudentId, arg2: ActivityRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveActivityRecordWithSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveActivityRecordWithSession(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveMonthlyAttendance(arg0: StudentId, arg1: MonthlyAttendance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMonthlyAttendance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMonthlyAttendance(arg0, arg1);
            return result;
        }
    }
    async saveMonthlyAttendanceWithSession(arg0: string, arg1: StudentId, arg2: MonthlyAttendance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMonthlyAttendanceWithSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMonthlyAttendanceWithSession(arg0, arg1, arg2);
            return result;
        }
    }
    async saveReportCard(arg0: StudentId, arg1: ReportCard): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReportCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReportCard(arg0, arg1);
            return result;
        }
    }
    async saveReportCardWithSession(arg0: string, arg1: StudentId, arg2: ReportCard): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReportCardWithSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReportCardWithSession(arg0, arg1, arg2);
            return result;
        }
    }
    async saveSportsRecord(arg0: StudentId, arg1: SportsRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSportsRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSportsRecord(arg0, arg1);
            return result;
        }
    }
    async saveSportsRecordWithSession(arg0: string, arg1: StudentId, arg2: SportsRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSportsRecordWithSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSportsRecordWithSession(arg0, arg1, arg2);
            return result;
        }
    }
    async saveStudentProfile(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStudentProfile(to_candid_StudentProfile_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStudentProfile(to_candid_StudentProfile_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveStudentProfileWithSession(arg0: string, arg1: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStudentProfileWithSession(arg0, to_candid_StudentProfile_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStudentProfileWithSession(arg0, to_candid_StudentProfile_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveSubjectMarks(arg0: StudentId, arg1: Array<SubjectMarks>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSubjectMarks(arg0, to_candid_vec_n52(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSubjectMarks(arg0, to_candid_vec_n52(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveSubjectMarksForSessionWithSession(arg0: string, arg1: StudentId, arg2: string, arg3: Array<SubjectMarks>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSubjectMarksForSessionWithSession(arg0, arg1, arg2, to_candid_vec_n52(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSubjectMarksForSessionWithSession(arg0, arg1, arg2, to_candid_vec_n52(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async saveSubjectMarksWithSession(arg0: string, arg1: StudentId, arg2: Array<SubjectMarks>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSubjectMarksWithSession(arg0, arg1, to_candid_vec_n52(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSubjectMarksWithSession(arg0, arg1, to_candid_vec_n52(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveTeacherAttendanceWithSession(arg0: string, arg1: TeacherMonthlyAttendance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTeacherAttendanceWithSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTeacherAttendanceWithSession(arg0, arg1);
            return result;
        }
    }
    async saveTeacherProfileWithSession(arg0: string, arg1: TeacherProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTeacherProfileWithSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTeacherProfileWithSession(arg0, arg1);
            return result;
        }
    }
    async searchStudents(arg0: string): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudents(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudents(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchStudentsWithSession(arg0: string, arg1: string): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudentsWithSession(arg0, arg1);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudentsWithSession(arg0, arg1);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async setCurrentAppSessionWithSession(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCurrentAppSessionWithSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCurrentAppSessionWithSession(arg0, arg1);
            return result;
        }
    }
    async setStudentIdForUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStudentIdForUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStudentIdForUserProfile(arg0);
            return result;
        }
    }
    async updateActivityRecordWithSession(arg0: string, arg1: StudentId, arg2: bigint, arg3: ActivityRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivityRecordWithSession(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivityRecordWithSession(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateSportsRecordWithSession(arg0: string, arg1: StudentId, arg2: string, arg3: SportsRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSportsRecordWithSession(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSportsRecordWithSession(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateUserPassword(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserPassword(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserPassword(arg0, arg1, arg2);
            return result;
        }
    }
    async uploadCircular(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ExternalBlob, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadCircular(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n47(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadCircular(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n47(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async uploadClassStudyMaterial(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: ExternalBlob, arg7: string, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadClassStudyMaterial(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_ExternalBlob_n47(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadClassStudyMaterial(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_ExternalBlob_n47(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
            return result;
        }
    }
    async uploadStudyMaterial(arg0: string, arg1: string, arg2: ExternalBlob, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadStudyMaterial(arg0, arg1, await to_candid_ExternalBlob_n47(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadStudyMaterial(arg0, arg1, await to_candid_ExternalBlob_n47(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async uploadStudyMaterialWithSession(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadStudyMaterialWithSession(arg0, arg1, arg2, await to_candid_ExternalBlob_n47(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadStudyMaterialWithSession(arg0, arg1, arg2, await to_candid_ExternalBlob_n47(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async validateSession(arg0: string): Promise<SessionInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_Circular_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Circular): Promise<Circular> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_ClassStudyMaterial_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassStudyMaterial): Promise<ClassStudyMaterial> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_NoticePost_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoticePost): Promise<NoticePost> {
    return await from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_SessionInfo_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionInfo): SessionInfo {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_StudentProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentProfile): StudentProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_StudyMaterial_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudyMaterial): Promise<StudyMaterial> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_SubjectMarks_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubjectMarks): SubjectMarks {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserAccount_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserAccount): UserAccount {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentId]): StudentId | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudyMaterial]): Promise<StudyMaterial | null> {
    return value.length === 0 ? null : await from_candid_StudyMaterial_n27(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        displayName: string;
        role: string;
        assignedClass: [] | [bigint];
        sessionToken: string;
    }]): {
    displayName: string;
    role: string;
    assignedClass?: bigint;
    sessionToken: string;
} | null {
    return value.length === 0 ? null : from_candid_record_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionInfo]): SessionInfo | null {
    return value.length === 0 ? null : from_candid_SessionInfo_n56(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marks: Array<_SubjectMarks>;
    reportCards: Array<_ReportCard>;
    activities: Array<_ActivityRecord>;
    attendance: Array<_MonthlyAttendance>;
    sports: Array<_SportsRecord>;
    profile: _StudentProfile;
}): {
    marks: Array<SubjectMarks>;
    reportCards: Array<ReportCard>;
    activities: Array<ActivityRecord>;
    attendance: Array<MonthlyAttendance>;
    sports: Array<SportsRecord>;
    profile: StudentProfile;
} {
    return {
        marks: from_candid_vec_n13(_uploadFile, _downloadFile, value.marks),
        reportCards: value.reportCards,
        activities: value.activities,
        attendance: value.attendance,
        sports: value.sports,
        profile: from_candid_StudentProfile_n16(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pen: string;
    tribe: string;
    contact: string;
    studentId: _StudentId;
    dateOfBirth: string;
    heightReopening: number;
    name: string;
    section: string;
    motherName: string;
    heightClosure: number;
    weightClosure: number;
    session: string;
    fatherName: string;
    bloodGroup: [] | [string];
    address: string;
    gender: string;
    classLevel: bigint;
    rollNo: string;
    religion: string;
    aadhar: string;
    weightReopening: number;
}): {
    pen: string;
    tribe: string;
    contact: string;
    studentId: StudentId;
    dateOfBirth: string;
    heightReopening: number;
    name: string;
    section: string;
    motherName: string;
    heightClosure: number;
    weightClosure: number;
    session: string;
    fatherName: string;
    bloodGroup?: string;
    address: string;
    gender: string;
    classLevel: bigint;
    rollNo: string;
    religion: string;
    aadhar: string;
    weightReopening: number;
} {
    return {
        pen: value.pen,
        tribe: value.tribe,
        contact: value.contact,
        studentId: value.studentId,
        dateOfBirth: value.dateOfBirth,
        heightReopening: value.heightReopening,
        name: value.name,
        section: value.section,
        motherName: value.motherName,
        heightClosure: value.heightClosure,
        weightClosure: value.weightClosure,
        session: value.session,
        fatherName: value.fatherName,
        bloodGroup: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.bloodGroup)),
        address: value.address,
        gender: value.gender,
        classLevel: value.classLevel,
        rollNo: value.rollNo,
        religion: value.religion,
        aadhar: value.aadhar,
        weightReopening: value.weightReopening
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: [] | [_StudentId];
    name: string;
}): {
    studentId?: StudentId;
    name: string;
} {
    return {
        studentId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.studentId)),
        name: value.name
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: _ExternalBlob;
    name: string;
    comments: string;
    uploadedBy: Principal;
}): Promise<{
    id: string;
    blob: ExternalBlob;
    name: string;
    comments: string;
    uploadedBy: Principal;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        comments: value.comments,
        uploadedBy: value.uploadedBy
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    fileBlob: _ExternalBlob;
    description: string;
    fileName: string;
    uploadedAt: string;
    uploadedBy: string;
}): Promise<{
    id: string;
    title: string;
    fileBlob: ExternalBlob;
    description: string;
    fileName: string;
    uploadedAt: string;
    uploadedBy: string;
}> {
    return {
        id: value.id,
        title: value.title,
        fileBlob: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.fileBlob),
        description: value.description,
        fileName: value.fileName,
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    subject: string;
    fileBlob: _ExternalBlob;
    description: string;
    fileName: string;
    classLevel: bigint;
    uploadedAt: string;
    uploadedBy: string;
}): Promise<{
    id: string;
    title: string;
    subject: string;
    fileBlob: ExternalBlob;
    description: string;
    fileName: string;
    classLevel: bigint;
    uploadedAt: string;
    uploadedBy: string;
}> {
    return {
        id: value.id,
        title: value.title,
        subject: value.subject,
        fileBlob: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.fileBlob),
        description: value.description,
        fileName: value.fileName,
        classLevel: value.classLevel,
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
async function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    hasFile: boolean;
    postedAt: string;
    postedBy: string;
    content: string;
    fileBlob: [] | [_ExternalBlob];
    fileName: string;
}): Promise<{
    id: string;
    title: string;
    hasFile: boolean;
    postedAt: string;
    postedBy: string;
    content: string;
    fileBlob?: ExternalBlob;
    fileName: string;
}> {
    return {
        id: value.id,
        title: value.title,
        hasFile: value.hasFile,
        postedAt: value.postedAt,
        postedBy: value.postedBy,
        content: value.content,
        fileBlob: record_opt_to_undefined(await from_candid_opt_n40(_uploadFile, _downloadFile, value.fileBlob)),
        fileName: value.fileName
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    displayName: string;
    password: string;
    role: string;
    assignedClass: [] | [bigint];
}): {
    username: string;
    displayName: string;
    password: string;
    role: string;
    assignedClass?: bigint;
} {
    return {
        username: value.username,
        displayName: value.displayName,
        password: value.password,
        role: value.role,
        assignedClass: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.assignedClass))
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    role: string;
    assignedClass: [] | [bigint];
    sessionToken: string;
}): {
    displayName: string;
    role: string;
    assignedClass?: bigint;
    sessionToken: string;
} {
    return {
        displayName: value.displayName,
        role: value.role,
        assignedClass: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.assignedClass)),
        sessionToken: value.sessionToken
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    displayName: string;
    role: string;
    assignedClass: [] | [bigint];
}): {
    username: string;
    displayName: string;
    role: string;
    assignedClass?: bigint;
} {
    return {
        username: value.username,
        displayName: value.displayName,
        role: value.role,
        assignedClass: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.assignedClass))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lowerClass: _LowerClassMarks;
} | {
    upperClass: _UpperClassMarks;
}): {
    __kind__: "lowerClass";
    lowerClass: LowerClassMarks;
} | {
    __kind__: "upperClass";
    upperClass: UpperClassMarks;
} {
    return "lowerClass" in value ? {
        __kind__: "lowerClass",
        lowerClass: value.lowerClass
    } : "upperClass" in value ? {
        __kind__: "upperClass",
        upperClass: value.upperClass
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubjectMarks>): Array<SubjectMarks> {
    return value.map((x)=>from_candid_SubjectMarks_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentProfile>): Array<StudentProfile> {
    return value.map((x)=>from_candid_StudentProfile_n16(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudyMaterial>): Promise<Array<StudyMaterial>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StudyMaterial_n27(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Circular>): Promise<Array<Circular>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Circular_n32(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClassStudyMaterial>): Promise<Array<ClassStudyMaterial>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ClassStudyMaterial_n35(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NoticePost>): Promise<Array<NoticePost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_NoticePost_n38(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserAccount>): Array<UserAccount> {
    return value.map((x)=>from_candid_UserAccount_n42(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_StudentProfile_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentProfile): _StudentProfile {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_SubjectMarks_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubjectMarks): _SubjectMarks {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_UserAccount_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserAccount): _UserAccount {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n47(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    displayName: string;
    password: string;
    role: string;
    assignedClass?: bigint;
}): {
    username: string;
    displayName: string;
    password: string;
    role: string;
    assignedClass: [] | [bigint];
} {
    return {
        username: value.username,
        displayName: value.displayName,
        password: value.password,
        role: value.role,
        assignedClass: value.assignedClass ? candid_some(value.assignedClass) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId?: StudentId;
    name: string;
}): {
    studentId: [] | [_StudentId];
    name: string;
} {
    return {
        studentId: value.studentId ? candid_some(value.studentId) : candid_none(),
        name: value.name
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pen: string;
    tribe: string;
    contact: string;
    studentId: StudentId;
    dateOfBirth: string;
    heightReopening: number;
    name: string;
    section: string;
    motherName: string;
    heightClosure: number;
    weightClosure: number;
    session: string;
    fatherName: string;
    bloodGroup?: string;
    address: string;
    gender: string;
    classLevel: bigint;
    rollNo: string;
    religion: string;
    aadhar: string;
    weightReopening: number;
}): {
    pen: string;
    tribe: string;
    contact: string;
    studentId: _StudentId;
    dateOfBirth: string;
    heightReopening: number;
    name: string;
    section: string;
    motherName: string;
    heightClosure: number;
    weightClosure: number;
    session: string;
    fatherName: string;
    bloodGroup: [] | [string];
    address: string;
    gender: string;
    classLevel: bigint;
    rollNo: string;
    religion: string;
    aadhar: string;
    weightReopening: number;
} {
    return {
        pen: value.pen,
        tribe: value.tribe,
        contact: value.contact,
        studentId: value.studentId,
        dateOfBirth: value.dateOfBirth,
        heightReopening: value.heightReopening,
        name: value.name,
        section: value.section,
        motherName: value.motherName,
        heightClosure: value.heightClosure,
        weightClosure: value.weightClosure,
        session: value.session,
        fatherName: value.fatherName,
        bloodGroup: value.bloodGroup ? candid_some(value.bloodGroup) : candid_none(),
        address: value.address,
        gender: value.gender,
        classLevel: value.classLevel,
        rollNo: value.rollNo,
        religion: value.religion,
        aadhar: value.aadhar,
        weightReopening: value.weightReopening
    };
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "lowerClass";
    lowerClass: LowerClassMarks;
} | {
    __kind__: "upperClass";
    upperClass: UpperClassMarks;
}): {
    lowerClass: _LowerClassMarks;
} | {
    upperClass: _UpperClassMarks;
} {
    return value.__kind__ === "lowerClass" ? {
        lowerClass: value.lowerClass
    } : value.__kind__ === "upperClass" ? {
        upperClass: value.upperClass
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SubjectMarks>): Array<_SubjectMarks> {
    return value.map((x)=>to_candid_SubjectMarks_n53(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
