/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LowerClassMarks {
    totalMarks: number;
    subjectName: string;
    writtenTest1: number;
    writtenTest2: number;
    writtenTest3: number;
    writtenTest4: number;
    grade: string;
    comprehensiveTest1: number;
    comprehensiveTest2: number;
    comprehensiveTest3: number;
    comprehensiveTest4: number;
    percentage: number;
}
export interface ReportCard {
    studentId: StudentId;
    term2Total: number;
    behaviour: string;
    rank: string;
    finalPercentage: number;
    session: string;
    sportsRemarks: string;
    grade: string;
    attendanceSummary: string;
    term1Total: number;
    remarks: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface SportsRecord {
    studentId: StudentId;
    game: string;
    level: string;
    event: string;
    entryId: string;
    session: string;
    position: string;
    remarks: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MonthlyAttendance {
    month: string;
    studentId: StudentId;
    present: bigint;
    totalDays: bigint;
    session: string;
    percentage: number;
}
export type StudentId = string;
export type SubjectMarks = {
    __kind__: "lowerClass";
    lowerClass: LowerClassMarks;
} | {
    __kind__: "upperClass";
    upperClass: UpperClassMarks;
};
export interface StudentProfile {
    pen: string;
    tribe: string;
    contact: string;
    studentId: StudentId;
    dateOfBirth: string;
    heightReopening: number;
    name: string;
    section: string;
    motherName: string;
    heightClosure: number;
    weightClosure: number;
    session: string;
    fatherName: string;
    address: string;
    gender: string;
    classLevel: bigint;
    rollNo: string;
    religion: string;
    aadhar: string;
    weightReopening: number;
}
export interface UpperClassMarks {
    nb1: number;
    nb2: number;
    pt1: number;
    pt2: number;
    se1: number;
    se2: number;
    term2Total: number;
    subjectName: string;
    term2Exam: number;
    finalPercentage: number;
    pt2Weightage: number;
    grade: string;
    pt1Weightage: number;
    term1Exam: number;
    term1Total: number;
}
export interface StudyMaterial {
    id: string;
    blob: ExternalBlob;
    name: string;
    comments: string;
    uploadedBy: Principal;
}
export interface ActivityRecord {
    activityType: string;
    studentId: StudentId;
    description: string;
    session: string;
    grade: string;
    remarks: string;
}
export interface UserProfile {
    studentId?: StudentId;
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getActivityRecords(studentId: StudentId): Promise<Array<ActivityRecord>>;
    getAllRecordsForStudent(studentId: StudentId): Promise<{
        marks: Array<SubjectMarks>;
        reportCards: Array<ReportCard>;
        activities: Array<ActivityRecord>;
        attendance: Array<MonthlyAttendance>;
        sports: Array<SportsRecord>;
        profile: StudentProfile;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMonthlyAttendance(studentId: StudentId): Promise<Array<MonthlyAttendance>>;
    getReportCards(studentId: StudentId): Promise<Array<ReportCard>>;
    getSportsRecords(studentId: StudentId): Promise<Array<SportsRecord>>;
    getStudentProfile(studentId: StudentId): Promise<StudentProfile>;
    getStudentsByClass(classLevel: bigint): Promise<Array<StudentProfile>>;
    getStudyMaterial(id: string): Promise<StudyMaterial | null>;
    getSubjectMarks(studentId: StudentId): Promise<Array<SubjectMarks>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllStudentProfiles(): Promise<Array<StudentProfile>>;
    listAllStudyMaterials(): Promise<Array<StudyMaterial>>;
    saveActivityRecord(studentId: StudentId, activity: ActivityRecord): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveMonthlyAttendance(studentId: StudentId, attendance: MonthlyAttendance): Promise<void>;
    saveReportCard(studentId: StudentId, report: ReportCard): Promise<void>;
    saveSportsRecord(studentId: StudentId, record: SportsRecord): Promise<void>;
    saveStudentProfile(profile: StudentProfile): Promise<void>;
    saveSubjectMarks(studentId: StudentId, marks: Array<SubjectMarks>): Promise<void>;
    searchStudents(searchTerm: string): Promise<Array<StudentProfile>>;
    uploadStudyMaterial(id: string, name: string, blob: ExternalBlob, comments: string): Promise<void>;
}
import type { ActivityRecord as _ActivityRecord, ExternalBlob as _ExternalBlob, LowerClassMarks as _LowerClassMarks, MonthlyAttendance as _MonthlyAttendance, ReportCard as _ReportCard, SportsRecord as _SportsRecord, StudentId as _StudentId, StudentProfile as _StudentProfile, StudyMaterial as _StudyMaterial, SubjectMarks as _SubjectMarks, UpperClassMarks as _UpperClassMarks, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getActivityRecords(arg0: StudentId): Promise<Array<ActivityRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityRecords(arg0);
            return result;
        }
    }
    async getAllRecordsForStudent(arg0: StudentId): Promise<{
        marks: Array<SubjectMarks>;
        reportCards: Array<ReportCard>;
        activities: Array<ActivityRecord>;
        attendance: Array<MonthlyAttendance>;
        sports: Array<SportsRecord>;
        profile: StudentProfile;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecordsForStudent(arg0);
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecordsForStudent(arg0);
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyAttendance(arg0: StudentId): Promise<Array<MonthlyAttendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyAttendance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyAttendance(arg0);
            return result;
        }
    }
    async getReportCards(arg0: StudentId): Promise<Array<ReportCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportCards(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportCards(arg0);
            return result;
        }
    }
    async getSportsRecords(arg0: StudentId): Promise<Array<SportsRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSportsRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSportsRecords(arg0);
            return result;
        }
    }
    async getStudentProfile(arg0: StudentId): Promise<StudentProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProfile(arg0);
            return result;
        }
    }
    async getStudentsByClass(arg0: bigint): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsByClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsByClass(arg0);
            return result;
        }
    }
    async getStudyMaterial(arg0: string): Promise<StudyMaterial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyMaterial(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyMaterial(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubjectMarks(arg0: StudentId): Promise<Array<SubjectMarks>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectMarks(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectMarks(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllStudentProfiles(): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStudentProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStudentProfiles();
            return result;
        }
    }
    async listAllStudyMaterials(): Promise<Array<StudyMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStudyMaterials();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStudyMaterials();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveActivityRecord(arg0: StudentId, arg1: ActivityRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveActivityRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveActivityRecord(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveMonthlyAttendance(arg0: StudentId, arg1: MonthlyAttendance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMonthlyAttendance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMonthlyAttendance(arg0, arg1);
            return result;
        }
    }
    async saveReportCard(arg0: StudentId, arg1: ReportCard): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReportCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReportCard(arg0, arg1);
            return result;
        }
    }
    async saveSportsRecord(arg0: StudentId, arg1: SportsRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSportsRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSportsRecord(arg0, arg1);
            return result;
        }
    }
    async saveStudentProfile(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStudentProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStudentProfile(arg0);
            return result;
        }
    }
    async saveSubjectMarks(arg0: StudentId, arg1: Array<SubjectMarks>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSubjectMarks(arg0, to_candid_vec_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSubjectMarks(arg0, to_candid_vec_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async searchStudents(arg0: string): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudents(arg0);
            return result;
        }
    }
    async uploadStudyMaterial(arg0: string, arg1: string, arg2: ExternalBlob, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadStudyMaterial(arg0, arg1, await to_candid_ExternalBlob_n30(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadStudyMaterial(arg0, arg1, await to_candid_ExternalBlob_n30(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_StudyMaterial_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudyMaterial): Promise<StudyMaterial> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_SubjectMarks_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubjectMarks): SubjectMarks {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentId]): StudentId | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudyMaterial]): Promise<StudyMaterial | null> {
    return value.length === 0 ? null : await from_candid_StudyMaterial_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marks: Array<_SubjectMarks>;
    reportCards: Array<_ReportCard>;
    activities: Array<_ActivityRecord>;
    attendance: Array<_MonthlyAttendance>;
    sports: Array<_SportsRecord>;
    profile: _StudentProfile;
}): {
    marks: Array<SubjectMarks>;
    reportCards: Array<ReportCard>;
    activities: Array<ActivityRecord>;
    attendance: Array<MonthlyAttendance>;
    sports: Array<SportsRecord>;
    profile: StudentProfile;
} {
    return {
        marks: from_candid_vec_n11(_uploadFile, _downloadFile, value.marks),
        reportCards: value.reportCards,
        activities: value.activities,
        attendance: value.attendance,
        sports: value.sports,
        profile: value.profile
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: [] | [_StudentId];
    name: string;
}): {
    studentId?: StudentId;
    name: string;
} {
    return {
        studentId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.studentId)),
        name: value.name
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: _ExternalBlob;
    name: string;
    comments: string;
    uploadedBy: Principal;
}): Promise<{
    id: string;
    blob: ExternalBlob;
    name: string;
    comments: string;
    uploadedBy: Principal;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        comments: value.comments,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lowerClass: _LowerClassMarks;
} | {
    upperClass: _UpperClassMarks;
}): {
    __kind__: "lowerClass";
    lowerClass: LowerClassMarks;
} | {
    __kind__: "upperClass";
    upperClass: UpperClassMarks;
} {
    return "lowerClass" in value ? {
        __kind__: "lowerClass",
        lowerClass: value.lowerClass
    } : "upperClass" in value ? {
        __kind__: "upperClass",
        upperClass: value.upperClass
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubjectMarks>): Array<SubjectMarks> {
    return value.map((x)=>from_candid_SubjectMarks_n12(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudyMaterial>): Promise<Array<StudyMaterial>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StudyMaterial_n21(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_SubjectMarks_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubjectMarks): _SubjectMarks {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId?: StudentId;
    name: string;
}): {
    studentId: [] | [_StudentId];
    name: string;
} {
    return {
        studentId: value.studentId ? candid_some(value.studentId) : candid_none(),
        name: value.name
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "lowerClass";
    lowerClass: LowerClassMarks;
} | {
    __kind__: "upperClass";
    upperClass: UpperClassMarks;
}): {
    lowerClass: _LowerClassMarks;
} | {
    upperClass: _UpperClassMarks;
} {
    return value.__kind__ === "lowerClass" ? {
        lowerClass: value.lowerClass
    } : value.__kind__ === "upperClass" ? {
        upperClass: value.upperClass
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SubjectMarks>): Array<_SubjectMarks> {
    return value.map((x)=>to_candid_SubjectMarks_n28(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
